#!/bin/bash

# rm -rf venv
# virtualenv -p /usr/bin/python3 venv/
# source venv/bin/activate
echo "Installing requisite modules..."
python3 pip install -U -r requirements.txt
echo "Installed all requisite modules!"
echo "Launching Crocodile Bot..."
cd crocbot
python3 __init__.py
